// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/wiki/wiki.proto

package wiki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 記事の状態
type ArticleStatus int32

const (
	ArticleStatus_ARTICLE_STATUS_UNSPECIFIED ArticleStatus = 0 // proto3の慣例: 0は「未指定」
	ArticleStatus_ARTICLE_STATUS_DRAFT       ArticleStatus = 1 // 下書き
	ArticleStatus_ARTICLE_STATUS_PUBLISHED   ArticleStatus = 2 // 公開済み
	ArticleStatus_ARTICLE_STATUS_ARCHIVED    ArticleStatus = 3 // アーカイブ
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNSPECIFIED",
		1: "ARTICLE_STATUS_DRAFT",
		2: "ARTICLE_STATUS_PUBLISHED",
		3: "ARTICLE_STATUS_ARCHIVED",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNSPECIFIED": 0,
		"ARTICLE_STATUS_DRAFT":       1,
		"ARTICLE_STATUS_PUBLISHED":   2,
		"ARTICLE_STATUS_ARCHIVED":    3,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wiki_wiki_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_proto_wiki_wiki_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{0}
}

// ユーザーロール
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ADMIN       Role = 1 // 投稿・編集可能（あなた）
	Role_ROLE_VIEWER      Role = 2 // 閲覧のみ（その他）
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ADMIN",
		2: "ROLE_VIEWER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ADMIN":       1,
		"ROLE_VIEWER":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wiki_wiki_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_proto_wiki_wiki_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{1}
}

// 記事の型を定義
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 記事を取得
type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 記事を返す
type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 特定の記事を取得
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 特定の記事を返す
type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 全記事を取得
type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{5}
}

// 複数の記事を返す
type ListArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       []*Article             `protobuf:"bytes,1,rep,name=article,proto3" json:"article,omitempty"` // 複数記事
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleResponse) Reset() {
	*x = ListArticleResponse{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleResponse) ProtoMessage() {}

func (x *ListArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleResponse.ProtoReflect.Descriptor instead.
func (*ListArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticleResponse) GetArticle() []*Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 記事を更新（部分更新）
type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

// 更新した記事を返す
type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// 特定の記事を削除
type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 削除した結果を返す
type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_proto_wiki_wiki_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wiki_wiki_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wiki_wiki_proto_rawDescGZIP(), []int{10}
}

var File_proto_wiki_wiki_proto protoreflect.FileDescriptor

const file_proto_wiki_wiki_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wiki/wiki.proto\x12\x04wiki\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbf\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"@\n" +
	"\x15CreateArticleResponse\x12'\n" +
	"\aarticle\x18\x01 \x01(\v2\r.wiki.ArticleR\aarticle\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12GetArticleResponse\x12'\n" +
	"\aArticle\x18\x01 \x01(\v2\r.wiki.ArticleR\aArticle\"\x14\n" +
	"\x12ListArticleRequest\">\n" +
	"\x13ListArticleResponse\x12'\n" +
	"\aarticle\x18\x01 \x03(\v2\r.wiki.ArticleR\aarticle\"v\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"@\n" +
	"\x15UpdateArticleResponse\x12'\n" +
	"\aarticle\x18\x01 \x01(\v2\r.wiki.ArticleR\aarticle\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteArticleResponse*\x84\x01\n" +
	"\rArticleStatus\x12\x1e\n" +
	"\x1aARTICLE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTICLE_STATUS_DRAFT\x10\x01\x12\x1c\n" +
	"\x18ARTICLE_STATUS_PUBLISHED\x10\x02\x12\x1b\n" +
	"\x17ARTICLE_STATUS_ARCHIVED\x10\x03*=\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x0f\n" +
	"\vROLE_VIEWER\x10\x022\xc9\x02\n" +
	"\fWikiServices\x12A\n" +
	"\x06Create\x12\x1a.wiki.CreateArticleRequest\x1a\x1b.wiki.CreateArticleResponse\x128\n" +
	"\x03Get\x12\x17.wiki.GetArticleRequest\x1a\x18.wiki.GetArticleResponse\x12;\n" +
	"\x04List\x12\x18.wiki.ListArticleRequest\x1a\x19.wiki.ListArticleResponse\x12A\n" +
	"\x06Update\x12\x1a.wiki.UpdateArticleRequest\x1a\x1b.wiki.UpdateArticleResponse\x12<\n" +
	"\x06Delete\x12\x1a.wiki.DeleteArticleRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/TenshoOHASHI/knowhub/proto/wikib\x06proto3"

var (
	file_proto_wiki_wiki_proto_rawDescOnce sync.Once
	file_proto_wiki_wiki_proto_rawDescData []byte
)

func file_proto_wiki_wiki_proto_rawDescGZIP() []byte {
	file_proto_wiki_wiki_proto_rawDescOnce.Do(func() {
		file_proto_wiki_wiki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wiki_wiki_proto_rawDesc), len(file_proto_wiki_wiki_proto_rawDesc)))
	})
	return file_proto_wiki_wiki_proto_rawDescData
}

var file_proto_wiki_wiki_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_wiki_wiki_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_wiki_wiki_proto_goTypes = []any{
	(ArticleStatus)(0),            // 0: wiki.ArticleStatus
	(Role)(0),                     // 1: wiki.Role
	(*Article)(nil),               // 2: wiki.Article
	(*CreateArticleRequest)(nil),  // 3: wiki.CreateArticleRequest
	(*CreateArticleResponse)(nil), // 4: wiki.CreateArticleResponse
	(*GetArticleRequest)(nil),     // 5: wiki.GetArticleRequest
	(*GetArticleResponse)(nil),    // 6: wiki.GetArticleResponse
	(*ListArticleRequest)(nil),    // 7: wiki.ListArticleRequest
	(*ListArticleResponse)(nil),   // 8: wiki.ListArticleResponse
	(*UpdateArticleRequest)(nil),  // 9: wiki.UpdateArticleRequest
	(*UpdateArticleResponse)(nil), // 10: wiki.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),  // 11: wiki.DeleteArticleRequest
	(*DeleteArticleResponse)(nil), // 12: wiki.DeleteArticleResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_proto_wiki_wiki_proto_depIdxs = []int32{
	13, // 0: wiki.Article.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: wiki.Article.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: wiki.CreateArticleResponse.article:type_name -> wiki.Article
	2,  // 3: wiki.GetArticleResponse.Article:type_name -> wiki.Article
	2,  // 4: wiki.ListArticleResponse.article:type_name -> wiki.Article
	2,  // 5: wiki.UpdateArticleResponse.article:type_name -> wiki.Article
	3,  // 6: wiki.WikiServices.Create:input_type -> wiki.CreateArticleRequest
	5,  // 7: wiki.WikiServices.Get:input_type -> wiki.GetArticleRequest
	7,  // 8: wiki.WikiServices.List:input_type -> wiki.ListArticleRequest
	9,  // 9: wiki.WikiServices.Update:input_type -> wiki.UpdateArticleRequest
	11, // 10: wiki.WikiServices.Delete:input_type -> wiki.DeleteArticleRequest
	4,  // 11: wiki.WikiServices.Create:output_type -> wiki.CreateArticleResponse
	6,  // 12: wiki.WikiServices.Get:output_type -> wiki.GetArticleResponse
	8,  // 13: wiki.WikiServices.List:output_type -> wiki.ListArticleResponse
	10, // 14: wiki.WikiServices.Update:output_type -> wiki.UpdateArticleResponse
	14, // 15: wiki.WikiServices.Delete:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_wiki_wiki_proto_init() }
func file_proto_wiki_wiki_proto_init() {
	if File_proto_wiki_wiki_proto != nil {
		return
	}
	file_proto_wiki_wiki_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wiki_wiki_proto_rawDesc), len(file_proto_wiki_wiki_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wiki_wiki_proto_goTypes,
		DependencyIndexes: file_proto_wiki_wiki_proto_depIdxs,
		EnumInfos:         file_proto_wiki_wiki_proto_enumTypes,
		MessageInfos:      file_proto_wiki_wiki_proto_msgTypes,
	}.Build()
	File_proto_wiki_wiki_proto = out.File
	file_proto_wiki_wiki_proto_goTypes = nil
	file_proto_wiki_wiki_proto_depIdxs = nil
}
