ALTER TABLE profiles ADD COLUMN avatar_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN twitter_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN linkedin_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN wantedly_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN skills VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN languages VARCHAR(2000) NOT NULL DEFAULT '';
