import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import KeyboardShortcuts from '@/components/KeyBoardShortcuts';
import { SidebarProvider } from '@/context/SidebarContext';
import Footer from '@/components/Footer';
import { ToastProvider } from '@/context/ToastContext';
import { AuthProvider } from '@/context/AuthContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='h-screen flex flex-col bg-white dark:bg-stone-900 text-black dark:text-stone-100 overflow-hidden'>
        <ToastProvider>
          <AuthProvider>
            <SidebarProvider>
              <Navbar />
              <main className='flex-1 overflow-hidden'>{children}</main>
            </SidebarProvider>
            <Footer />
            <KeyboardShortcuts />
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
