// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *Source) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *Source) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArticleId      string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,4,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResult) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SummarizeRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type SummarizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type QuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SearchEngine  string                 `protobuf:"bytes,4,opt,name=search_engine,json=searchEngine,proto3" json:"search_engine,omitempty"` // "bm25", "vector", "hybrid", "graph"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionRequest) Reset() {
	*x = QuestionRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionRequest) ProtoMessage() {}

func (x *QuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionRequest.ProtoReflect.Descriptor instead.
func (*QuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QuestionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *QuestionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *QuestionRequest) GetSearchEngine() string {
	if x != nil {
		return x.SearchEngine
	}
	return ""
}

type QuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []*Source              `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuestionResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

// ナレッジグラフ関連
type EntityNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ArticleIds    []string               `protobuf:"bytes,4,rep,name=article_ids,json=articleIds,proto3" json:"article_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityNode) Reset() {
	*x = EntityNode{}
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityNode) ProtoMessage() {}

func (x *EntityNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityNode.ProtoReflect.Descriptor instead.
func (*EntityNode) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *EntityNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityNode) GetArticleIds() []string {
	if x != nil {
		return x.ArticleIds
	}
	return nil
}

type RelationEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationEdge) Reset() {
	*x = RelationEdge{}
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationEdge) ProtoMessage() {}

func (x *RelationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationEdge.ProtoReflect.Descriptor instead.
func (*RelationEdge) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{9}
}

func (x *RelationEdge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RelationEdge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RelationEdge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetKnowledgeGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeGraphRequest) Reset() {
	*x = GetKnowledgeGraphRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeGraphRequest) ProtoMessage() {}

func (x *GetKnowledgeGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeGraphRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{10}
}

type GetKnowledgeGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityNode          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Relations     []*RelationEdge        `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeGraphResponse) Reset() {
	*x = GetKnowledgeGraphResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeGraphResponse) ProtoMessage() {}

func (x *GetKnowledgeGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeGraphResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{11}
}

func (x *GetKnowledgeGraphResponse) GetEntities() []*EntityNode {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *GetKnowledgeGraphResponse) GetRelations() []*RelationEdge {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GetRelatedArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	MaxHops       int32                  `protobuf:"varint,2,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedArticlesRequest) Reset() {
	*x = GetRelatedArticlesRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedArticlesRequest) ProtoMessage() {}

func (x *GetRelatedArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetRelatedArticlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{12}
}

func (x *GetRelatedArticlesRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *GetRelatedArticlesRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *GetRelatedArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRelatedArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedArticlesResponse) Reset() {
	*x = GetRelatedArticlesResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedArticlesResponse) ProtoMessage() {}

func (x *GetRelatedArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetRelatedArticlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{13}
}

func (x *GetRelatedArticlesResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type InvalidateGraphCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateGraphCacheRequest) Reset() {
	*x = InvalidateGraphCacheRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateGraphCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateGraphCacheRequest) ProtoMessage() {}

func (x *InvalidateGraphCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateGraphCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateGraphCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{14}
}

type InvalidateGraphCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateGraphCacheResponse) Reset() {
	*x = InvalidateGraphCacheResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateGraphCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateGraphCacheResponse) ProtoMessage() {}

func (x *InvalidateGraphCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateGraphCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateGraphCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{15}
}

// ReAct Agent
type AgentQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Question        string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey          string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SearchEngine    string                 `protobuf:"bytes,4,opt,name=search_engine,json=searchEngine,proto3" json:"search_engine,omitempty"`
	EnableWebSearch bool                   `protobuf:"varint,5,opt,name=enable_web_search,json=enableWebSearch,proto3" json:"enable_web_search,omitempty"`
	History         string                 `protobuf:"bytes,6,opt,name=history,proto3" json:"history,omitempty"` // JSON: [{"role":"user","content":"..."}, ...]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentQuestionRequest) Reset() {
	*x = AgentQuestionRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentQuestionRequest) ProtoMessage() {}

func (x *AgentQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentQuestionRequest.ProtoReflect.Descriptor instead.
func (*AgentQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{16}
}

func (x *AgentQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AgentQuestionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentQuestionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AgentQuestionRequest) GetSearchEngine() string {
	if x != nil {
		return x.SearchEngine
	}
	return ""
}

func (x *AgentQuestionRequest) GetEnableWebSearch() bool {
	if x != nil {
		return x.EnableWebSearch
	}
	return false
}

func (x *AgentQuestionRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

type AgentStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thought       string                 `protobuf:"bytes,1,opt,name=thought,proto3" json:"thought,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ActionInput   string                 `protobuf:"bytes,3,opt,name=action_input,json=actionInput,proto3" json:"action_input,omitempty"`
	Observation   string                 `protobuf:"bytes,4,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStep) Reset() {
	*x = AgentStep{}
	mi := &file_proto_ai_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStep) ProtoMessage() {}

func (x *AgentStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStep.ProtoReflect.Descriptor instead.
func (*AgentStep) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{17}
}

func (x *AgentStep) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

func (x *AgentStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentStep) GetActionInput() string {
	if x != nil {
		return x.ActionInput
	}
	return ""
}

func (x *AgentStep) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

type AgentSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSource) Reset() {
	*x = AgentSource{}
	mi := &file_proto_ai_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSource) ProtoMessage() {}

func (x *AgentSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSource.ProtoReflect.Descriptor instead.
func (*AgentSource) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{18}
}

func (x *AgentSource) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *AgentSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgentQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Steps         []*AgentStep           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Sources       []*AgentSource         `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentQuestionResponse) Reset() {
	*x = AgentQuestionResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentQuestionResponse) ProtoMessage() {}

func (x *AgentQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentQuestionResponse.ProtoReflect.Descriptor instead.
func (*AgentQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{19}
}

func (x *AgentQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AgentQuestionResponse) GetSteps() []*AgentStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *AgentQuestionResponse) GetSources() []*AgentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_proto_ai_ai_proto protoreflect.FileDescriptor

const file_proto_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ai/ai.proto\x12\x02ai\"=\n" +
	"\x06Source\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x86\x01\n" +
	"\fSearchResult\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x0frelevance_score\x18\x04 \x01(\x01R\x0erelevanceScore\"<\n" +
	"\x0eSearchResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.ai.SearchResultR\aresults\"1\n" +
	"\x10SummarizeRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"-\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"\x81\x01\n" +
	"\x0fQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12#\n" +
	"\rsearch_engine\x18\x04 \x01(\tR\fsearchEngine\"P\n" +
	"\x10QuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12$\n" +
	"\asources\x18\x02 \x03(\v2\n" +
	".ai.SourceR\asources\"e\n" +
	"\n" +
	"EntityNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\varticle_ids\x18\x04 \x03(\tR\n" +
	"articleIds\"T\n" +
	"\fRelationEdge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x1a\n" +
	"\x18GetKnowledgeGraphRequest\"w\n" +
	"\x19GetKnowledgeGraphResponse\x12*\n" +
	"\bentities\x18\x01 \x03(\v2\x0e.ai.EntityNodeR\bentities\x12.\n" +
	"\trelations\x18\x02 \x03(\v2\x10.ai.RelationEdgeR\trelations\"k\n" +
	"\x19GetRelatedArticlesRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x19\n" +
	"\bmax_hops\x18\x02 \x01(\x05R\amaxHops\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"H\n" +
	"\x1aGetRelatedArticlesResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.ai.SearchResultR\aresults\"\x1d\n" +
	"\x1bInvalidateGraphCacheRequest\"\x1e\n" +
	"\x1cInvalidateGraphCacheResponse\"\xcc\x01\n" +
	"\x14AgentQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12#\n" +
	"\rsearch_engine\x18\x04 \x01(\tR\fsearchEngine\x12*\n" +
	"\x11enable_web_search\x18\x05 \x01(\bR\x0fenableWebSearch\x12\x18\n" +
	"\ahistory\x18\x06 \x01(\tR\ahistory\"\x82\x01\n" +
	"\tAgentStep\x12\x18\n" +
	"\athought\x18\x01 \x01(\tR\athought\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12!\n" +
	"\faction_input\x18\x03 \x01(\tR\vactionInput\x12 \n" +
	"\vobservation\x18\x04 \x01(\tR\vobservation\"T\n" +
	"\vAgentSource\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x7f\n" +
	"\x15AgentQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12#\n" +
	"\x05steps\x18\x02 \x03(\v2\r.ai.AgentStepR\x05steps\x12)\n" +
	"\asources\x18\x03 \x03(\v2\x0f.ai.AgentSourceR\asources2\x86\x04\n" +
	"\tAIService\x127\n" +
	"\x0eSearchArticles\x12\x11.ai.SearchRequest\x1a\x12.ai.SearchResponse\x12?\n" +
	"\x10SummarizeArticle\x12\x14.ai.SummarizeRequest\x1a\x15.ai.SummarizeResponse\x128\n" +
	"\vAskQuestion\x12\x13.ai.QuestionRequest\x1a\x14.ai.QuestionResponse\x12C\n" +
	"\fAskWithAgent\x12\x18.ai.AgentQuestionRequest\x1a\x19.ai.AgentQuestionResponse\x12P\n" +
	"\x11GetKnowledgeGraph\x12\x1c.ai.GetKnowledgeGraphRequest\x1a\x1d.ai.GetKnowledgeGraphResponse\x12S\n" +
	"\x12GetRelatedArticles\x12\x1d.ai.GetRelatedArticlesRequest\x1a\x1e.ai.GetRelatedArticlesResponse\x12Y\n" +
	"\x14InvalidateGraphCache\x12\x1f.ai.InvalidateGraphCacheRequest\x1a .ai.InvalidateGraphCacheResponseB*Z(github.com/TenshoOHASHI/knowhub/proto/aib\x06proto3"

var (
	file_proto_ai_ai_proto_rawDescOnce sync.Once
	file_proto_ai_ai_proto_rawDescData []byte
)

func file_proto_ai_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)))
	})
	return file_proto_ai_ai_proto_rawDescData
}

var file_proto_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_ai_ai_proto_goTypes = []any{
	(*Source)(nil),                       // 0: ai.Source
	(*SearchRequest)(nil),                // 1: ai.SearchRequest
	(*SearchResult)(nil),                 // 2: ai.SearchResult
	(*SearchResponse)(nil),               // 3: ai.SearchResponse
	(*SummarizeRequest)(nil),             // 4: ai.SummarizeRequest
	(*SummarizeResponse)(nil),            // 5: ai.SummarizeResponse
	(*QuestionRequest)(nil),              // 6: ai.QuestionRequest
	(*QuestionResponse)(nil),             // 7: ai.QuestionResponse
	(*EntityNode)(nil),                   // 8: ai.EntityNode
	(*RelationEdge)(nil),                 // 9: ai.RelationEdge
	(*GetKnowledgeGraphRequest)(nil),     // 10: ai.GetKnowledgeGraphRequest
	(*GetKnowledgeGraphResponse)(nil),    // 11: ai.GetKnowledgeGraphResponse
	(*GetRelatedArticlesRequest)(nil),    // 12: ai.GetRelatedArticlesRequest
	(*GetRelatedArticlesResponse)(nil),   // 13: ai.GetRelatedArticlesResponse
	(*InvalidateGraphCacheRequest)(nil),  // 14: ai.InvalidateGraphCacheRequest
	(*InvalidateGraphCacheResponse)(nil), // 15: ai.InvalidateGraphCacheResponse
	(*AgentQuestionRequest)(nil),         // 16: ai.AgentQuestionRequest
	(*AgentStep)(nil),                    // 17: ai.AgentStep
	(*AgentSource)(nil),                  // 18: ai.AgentSource
	(*AgentQuestionResponse)(nil),        // 19: ai.AgentQuestionResponse
}
var file_proto_ai_ai_proto_depIdxs = []int32{
	2,  // 0: ai.SearchResponse.results:type_name -> ai.SearchResult
	0,  // 1: ai.QuestionResponse.sources:type_name -> ai.Source
	8,  // 2: ai.GetKnowledgeGraphResponse.entities:type_name -> ai.EntityNode
	9,  // 3: ai.GetKnowledgeGraphResponse.relations:type_name -> ai.RelationEdge
	2,  // 4: ai.GetRelatedArticlesResponse.results:type_name -> ai.SearchResult
	17, // 5: ai.AgentQuestionResponse.steps:type_name -> ai.AgentStep
	18, // 6: ai.AgentQuestionResponse.sources:type_name -> ai.AgentSource
	1,  // 7: ai.AIService.SearchArticles:input_type -> ai.SearchRequest
	4,  // 8: ai.AIService.SummarizeArticle:input_type -> ai.SummarizeRequest
	6,  // 9: ai.AIService.AskQuestion:input_type -> ai.QuestionRequest
	16, // 10: ai.AIService.AskWithAgent:input_type -> ai.AgentQuestionRequest
	10, // 11: ai.AIService.GetKnowledgeGraph:input_type -> ai.GetKnowledgeGraphRequest
	12, // 12: ai.AIService.GetRelatedArticles:input_type -> ai.GetRelatedArticlesRequest
	14, // 13: ai.AIService.InvalidateGraphCache:input_type -> ai.InvalidateGraphCacheRequest
	3,  // 14: ai.AIService.SearchArticles:output_type -> ai.SearchResponse
	5,  // 15: ai.AIService.SummarizeArticle:output_type -> ai.SummarizeResponse
	7,  // 16: ai.AIService.AskQuestion:output_type -> ai.QuestionResponse
	19, // 17: ai.AIService.AskWithAgent:output_type -> ai.AgentQuestionResponse
	11, // 18: ai.AIService.GetKnowledgeGraph:output_type -> ai.GetKnowledgeGraphResponse
	13, // 19: ai.AIService.GetRelatedArticles:output_type -> ai.GetRelatedArticlesResponse
	15, // 20: ai.AIService.InvalidateGraphCache:output_type -> ai.InvalidateGraphCacheResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_proto_init() }
func file_proto_ai_ai_proto_init() {
	if File_proto_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_proto = out.File
	file_proto_ai_ai_proto_goTypes = nil
	file_proto_ai_ai_proto_depIdxs = nil
}
