  ALTER TABLE articles ADD COLUMN  category_id DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER content;

  ALTER TABLE articles ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER content;
