// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/profile/profile.proto

package profile

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 自己紹介
type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,4,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ポートフォリオアイテム
type PortfolioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`             // プロジェクト名
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 説明
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                 // URL
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`           // "developing" / "completed"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortfolioItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PortfolioItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PortfolioItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PortfolioItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PortfolioItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{2}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=Profile,proto3" json:"Profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,3,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// --- Portfolio RPCs ---
type CreatePortfolioItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePortfolioItemRequest) Reset() {
	*x = CreatePortfolioItemRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortfolioItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioItemRequest) ProtoMessage() {}

func (x *CreatePortfolioItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioItemRequest.ProtoReflect.Descriptor instead.
func (*CreatePortfolioItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePortfolioItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePortfolioItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePortfolioItemRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreatePortfolioItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreatePortfolioItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *PortfolioItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePortfolioItemResponse) Reset() {
	*x = CreatePortfolioItemResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortfolioItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioItemResponse) ProtoMessage() {}

func (x *CreatePortfolioItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioItemResponse.ProtoReflect.Descriptor instead.
func (*CreatePortfolioItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePortfolioItemResponse) GetItem() *PortfolioItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListPortfolioItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortfolioItemsRequest) Reset() {
	*x = ListPortfolioItemsRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortfolioItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortfolioItemsRequest) ProtoMessage() {}

func (x *ListPortfolioItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortfolioItemsRequest.ProtoReflect.Descriptor instead.
func (*ListPortfolioItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{8}
}

type ListPortfolioItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PortfolioItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortfolioItemsResponse) Reset() {
	*x = ListPortfolioItemsResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortfolioItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortfolioItemsResponse) ProtoMessage() {}

func (x *ListPortfolioItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortfolioItemsResponse.ProtoReflect.Descriptor instead.
func (*ListPortfolioItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{9}
}

func (x *ListPortfolioItemsResponse) GetItems() []*PortfolioItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdatePortfolioItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortfolioItemRequest) Reset() {
	*x = UpdatePortfolioItemRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortfolioItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortfolioItemRequest) ProtoMessage() {}

func (x *UpdatePortfolioItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortfolioItemRequest.ProtoReflect.Descriptor instead.
func (*UpdatePortfolioItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePortfolioItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePortfolioItemRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePortfolioItemRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePortfolioItemRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *UpdatePortfolioItemRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdatePortfolioItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *PortfolioItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortfolioItemResponse) Reset() {
	*x = UpdatePortfolioItemResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortfolioItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortfolioItemResponse) ProtoMessage() {}

func (x *UpdatePortfolioItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortfolioItemResponse.ProtoReflect.Descriptor instead.
func (*UpdatePortfolioItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePortfolioItemResponse) GetItem() *PortfolioItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeletePortfolioItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePortfolioItemRequest) Reset() {
	*x = DeletePortfolioItemRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePortfolioItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePortfolioItemRequest) ProtoMessage() {}

func (x *DeletePortfolioItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePortfolioItemRequest.ProtoReflect.Descriptor instead.
func (*DeletePortfolioItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePortfolioItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_profile_profile_proto protoreflect.FileDescriptor

const file_proto_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/profile/profile.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"github_url\x18\x04 \x01(\tR\tgithubUrl\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x01\n" +
	"\rPortfolioItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x13\n" +
	"\x11GetProfileRequest\"=\n" +
	"\x12GetProfileResponse\x12'\n" +
	"\aProfile\x18\x01 \x01(\v2\r.auth.ProfileR\aProfile\"]\n" +
	"\x14UpdateProfileRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"github_url\x18\x03 \x01(\tR\tgithubUrl\"@\n" +
	"\x15UpdateProfileResponse\x12'\n" +
	"\aprofile\x18\x01 \x01(\v2\r.auth.ProfileR\aprofile\"~\n" +
	"\x1aCreatePortfolioItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"F\n" +
	"\x1bCreatePortfolioItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.auth.PortfolioItemR\x04item\"\x1b\n" +
	"\x19ListPortfolioItemsRequest\"G\n" +
	"\x1aListPortfolioItemsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.auth.PortfolioItemR\x05items\"\xcf\x01\n" +
	"\x1aUpdatePortfolioItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x02R\x03url\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x03R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_urlB\t\n" +
	"\a_status\"F\n" +
	"\x1bUpdatePortfolioItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.auth.PortfolioItemR\x04item\",\n" +
	"\x1aDeletePortfolioItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xfd\x03\n" +
	"\x0eProfileService\x12?\n" +
	"\n" +
	"GetProfile\x12\x17.auth.GetProfileRequest\x1a\x18.auth.GetProfileResponse\x12H\n" +
	"\rUpdateProfile\x12\x1a.auth.UpdateProfileRequest\x1a\x1b.auth.UpdateProfileResponse\x12Z\n" +
	"\x13CreatePortfolioItem\x12 .auth.CreatePortfolioItemRequest\x1a!.auth.CreatePortfolioItemResponse\x12W\n" +
	"\x12ListPortfolioItems\x12\x1f.auth.ListPortfolioItemsRequest\x1a .auth.ListPortfolioItemsResponse\x12Z\n" +
	"\x13UpdatePortfolioItem\x12 .auth.UpdatePortfolioItemRequest\x1a!.auth.UpdatePortfolioItemResponse\x12O\n" +
	"\x13DeletePortfolioItem\x12 .auth.DeletePortfolioItemRequest\x1a\x16.google.protobuf.EmptyB/Z-github.com/TenshoOHASHI/knowhub/proto/profileb\x06proto3"

var (
	file_proto_profile_profile_proto_rawDescOnce sync.Once
	file_proto_profile_profile_proto_rawDescData []byte
)

func file_proto_profile_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)))
	})
	return file_proto_profile_profile_proto_rawDescData
}

var file_proto_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_profile_profile_proto_goTypes = []any{
	(*Profile)(nil),                     // 0: auth.Profile
	(*PortfolioItem)(nil),               // 1: auth.PortfolioItem
	(*GetProfileRequest)(nil),           // 2: auth.GetProfileRequest
	(*GetProfileResponse)(nil),          // 3: auth.GetProfileResponse
	(*UpdateProfileRequest)(nil),        // 4: auth.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 5: auth.UpdateProfileResponse
	(*CreatePortfolioItemRequest)(nil),  // 6: auth.CreatePortfolioItemRequest
	(*CreatePortfolioItemResponse)(nil), // 7: auth.CreatePortfolioItemResponse
	(*ListPortfolioItemsRequest)(nil),   // 8: auth.ListPortfolioItemsRequest
	(*ListPortfolioItemsResponse)(nil),  // 9: auth.ListPortfolioItemsResponse
	(*UpdatePortfolioItemRequest)(nil),  // 10: auth.UpdatePortfolioItemRequest
	(*UpdatePortfolioItemResponse)(nil), // 11: auth.UpdatePortfolioItemResponse
	(*DeletePortfolioItemRequest)(nil),  // 12: auth.DeletePortfolioItemRequest
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_proto_profile_profile_proto_depIdxs = []int32{
	13, // 0: auth.Profile.updated_at:type_name -> google.protobuf.Timestamp
	13, // 1: auth.PortfolioItem.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: auth.GetProfileResponse.Profile:type_name -> auth.Profile
	0,  // 3: auth.UpdateProfileResponse.profile:type_name -> auth.Profile
	1,  // 4: auth.CreatePortfolioItemResponse.item:type_name -> auth.PortfolioItem
	1,  // 5: auth.ListPortfolioItemsResponse.items:type_name -> auth.PortfolioItem
	1,  // 6: auth.UpdatePortfolioItemResponse.item:type_name -> auth.PortfolioItem
	2,  // 7: auth.ProfileService.GetProfile:input_type -> auth.GetProfileRequest
	4,  // 8: auth.ProfileService.UpdateProfile:input_type -> auth.UpdateProfileRequest
	6,  // 9: auth.ProfileService.CreatePortfolioItem:input_type -> auth.CreatePortfolioItemRequest
	8,  // 10: auth.ProfileService.ListPortfolioItems:input_type -> auth.ListPortfolioItemsRequest
	10, // 11: auth.ProfileService.UpdatePortfolioItem:input_type -> auth.UpdatePortfolioItemRequest
	12, // 12: auth.ProfileService.DeletePortfolioItem:input_type -> auth.DeletePortfolioItemRequest
	3,  // 13: auth.ProfileService.GetProfile:output_type -> auth.GetProfileResponse
	5,  // 14: auth.ProfileService.UpdateProfile:output_type -> auth.UpdateProfileResponse
	7,  // 15: auth.ProfileService.CreatePortfolioItem:output_type -> auth.CreatePortfolioItemResponse
	9,  // 16: auth.ProfileService.ListPortfolioItems:output_type -> auth.ListPortfolioItemsResponse
	11, // 17: auth.ProfileService.UpdatePortfolioItem:output_type -> auth.UpdatePortfolioItemResponse
	14, // 18: auth.ProfileService.DeletePortfolioItem:output_type -> google.protobuf.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_profile_profile_proto_init() }
func file_proto_profile_profile_proto_init() {
	if File_proto_profile_profile_proto != nil {
		return
	}
	file_proto_profile_profile_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_profile_proto = out.File
	file_proto_profile_profile_proto_goTypes = nil
	file_proto_profile_profile_proto_depIdxs = nil
}
